// <auto-generated />
using System;
using GBI.Teste.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBI.Teste.Repository.Migrations
{
    [DbContext(typeof(GBITesteSqlContext))]
    partial class GBITesteSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("GBI.Teste.Model.Cadastro.UsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char")
                        .HasAnnotation("Relational:JsonPropertyName", "cpf");

                    b.Property<long>("Celular")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "celular");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DateTime")
                        .HasAnnotation("Relational:JsonPropertyName", "dataCadastro");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime")
                        .HasAnnotation("Relational:JsonPropertyName", "dataEmissao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("Varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "nome");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "rg");

                    b.HasKey("Id");

                    b.ToTable("tb_gbi_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
